Win condition and game state
Saplings-Projects/Birthday-2024 pull request #8
Opened 2023-12-13 08:47 UTC by BishopJohnson

# Description

Added game states to `GameManager` to handle play and win states.

## Related issue(s)

https://github.com/Saplings-Projects/Birthday-2024/issues/4

## List of changes

A more detailed list of the changes.

### Added
- Signal to `GridLogic` to emit event when a tile is placed
- Getter for free spaces to `GridLogic`
- `GameState` class
- `GameEmptyState` class
- `GamePlayState` class
- `GameWinState` class
- Game states to `GameManager`

## Tests

None

## Additional notes

I think game states could be a good way of splitting up some game logic and make it easier to manage things. Such as making pieces only interactable during play state.

2023-12-14 06:11 UTC, Mikotey commented on Birthday-2024-Project/Scripts/GameManager.gd
This is named "GameManager" as that was its name when I copied it over, but that's a bit of a misnomer. It's more like the PlayerController for manipulating pieces in the scene

We should probably have the state logic implemented in a separate object that fires off events, if that's easy enough to do. Wonder if we should rename the GameManager to "PieceManipulator" or something... sounds like a pain since people have already forked off with it named GameManager

2023-12-14 06:24 UTC, Mikotey requested changes

2023-12-14 06:24 UTC, Mikotey commented on Birthday-2024-Project/Scripts/Game/States/GameWinState.gd
You have the win check and a state change that we can use to disable level input or other such effects, but there is still more to do. There is also the task of invoking a popup/screen/overlay that can act as the victory screen.

Some hindsight prerequisites:
1. needs to say "victory" or "win" or "complete" or something along those lines in text
2. needs to have buttons that can be used to navigate to other screens. For now, let's just have a button that reloads the scene
3. should disable the ability to interact with the level. In Unity, I usually just have an invisible UI element to block the input from reaching the level behind. I'm not sure if Godot has a similar option available, or if you have an alternative method you would prefer

2023-12-14 22:19 UTC, BishopJohnson commented on Birthday-2024-Project/Scripts/GameManager.gd
In terms of the puzzle, we could transfer stuff over to a "PuzzleController" that has states which handle different phases of the puzzle, like having the functionality for moving pieces around in a "PlayState" so that once the player enters the "WinState" they can't manipulate pieces anymore.

This should also make it easier if multiple people need to work on something for the puzzles since the functionality is split up into different files.

2023-12-14 22:25 UTC, BishopJohnson commented on Birthday-2024-Project/Scripts/Game/States/GameWinState.gd
As I mentioned in the other [comment](https://github.com/Saplings-Projects/Birthday-2024/pull/8#discussion_r1427360490), I think it may be preferable to separate functions into different states. But I don't want to do a big rework without getting the groups opinion.

I can work on the UI elements and I'll try to implement a basic disabler for input that we can revisit later if that's alright.

2023-12-15 03:11 UTC, Mikotey commented on Birthday-2024-Project/Scripts/Game/States/GameWinState.gd
That would probably be for the best in the long run, but developments are still being made by others at the moment. Maybe once the tasking around the level is resolved and we've moved on to developing the other screens, we can consider such a change.
Though, this isn't a big project. With Sambino's tween animations, a lot of gameplay is pretty much done. We could probably do a fast implementation and leave it at that.

2023-12-16 05:37 UTC, Mikotey approved these changes
Looks good to me!
We can make it look nicer once we have the mockups and art for a proper victory screen

2023-12-16 05:37 UTC, merged